import {
  createData,
  createOrganizationData,
} from '../../utils/repository-utils';

export const getDataForRepositories = () => [
  createData(
    1,
    'Cupcake',
    'https://github.com/cupcake',
    'Progress',
    'org/desert',
    3,
  ),
  createData(2, 'Donut', 'https://github.com/donut', 'Done', 'org/donut'),
  createData(
    3,
    'Eclair',
    'https://github.com/eclair',
    'Failed',
    'org/desert',
    2,
  ),
  createData(
    4,
    'Frozen yoghurt',
    'https://github.com/yogurt',
    '',
    'org/desert',
    0,
  ),
  createData(
    5,
    'Gingerbread',
    'https://github.com/gingerbread',
    'Exists',
    'org/desert',
    0,
  ),
  createData(9, 'KitKat', 'https://github.com/kitkat', '', 'org/desert', 0),
  createData(13, 'Oreo', 'https://github.com/oreo', '', 'org/desert', 0),
  createData(
    10,
    'food-app',
    'https://github.com/food-app',
    'Progress',
    'org/pet-store-boston',
    0,
  ),
  createData(
    11,
    'online-store',
    'https://github.com/online-store',
    'Done',
    'org/pet-store-boston',
    0,
  ),
  createData(
    12,
    'pet-app',
    'https://github.com/pet-app',
    'Failed',
    'org/pet-store-boston',
    0,
  ),
];

export const getDataForOrganizations = () => [
  createOrganizationData(
    1,
    'org/pet-store-boston',
    'https://github.com/pet-store-boston',
    [
      {
        id: 10,
        name: 'food-app',
        repoURL: 'https://github.com/food-app',
        status: 'Progress',
        organization: 'org/pet-store-boston',
        lastUpdated: '',
      },
      {
        id: 11,
        name: 'online-store',
        repoURL: 'https://github.com/online-store',
        status: 'Done',
        organization: 'org/pet-store-boston',
        lastUpdated: '',
      },
      {
        id: 12,
        name: 'pet-app',
        repoURL: 'https://github.com/pet-app',
        status: 'Failed',
        organization: 'org/pet-store-boston',
        lastUpdated: '',
      },
    ],
    {
      yaml: '',
      status: '',
    },
  ),
  createOrganizationData(
    2,
    'org/desert',
    'https://github.com/desert',
    [
      {
        id: 1,
        name: 'Cupcake',
        repoURL: 'https://github.com/cupcake',
        status: 'Progress',
        organization: 'org/desert',
        lastUpdated: '',
      },
      {
        id: 2,
        name: 'Donut',
        repoURL: 'https://github.com/donut',
        status: 'Done',
        organization: 'org/desert',
        lastUpdated: '',
      },
      {
        id: 3,
        name: 'Eclair',
        repoURL: 'https://github.com/eclair',
        status: 'Failed',
        organization: 'org/desert',
        lastUpdated: '',
      },
      {
        id: 4,
        name: 'Frozen yoghurt',
        repoURL: 'https://github.com/yogurt',
        status: '',
        organization: 'org/desert',
        lastUpdated: '',
      },
      {
        id: 5,
        name: 'Gingerbread',
        repoURL: 'https://github.com/gingerbread',
        status: 'Exists',
        organization: 'org/desert',
        lastUpdated: '',
      },
      {
        id: 9,
        name: 'KitKat',
        repoURL: 'https://github.com/kitkat',
        status: '',
        organization: 'org/desert',
        lastUpdated: '',
      },
      {
        id: 13,
        name: 'Oreo',
        repoURL: 'https://github.com/oreo',
        status: '',
        organization: 'org/desert',
        lastUpdated: '',
      },
    ],
    {
      yaml: '',
      status: '',
    },
  ),
];
